apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "eu-jap-hack.fullname" . }}-waltid-wallet
  labels:
    {{- include "eu-jap-hack.labels" . | nindent 4 }}
    app.kubernetes.io/component: waltid-wallet-api
data:
  db.conf: |
    db {
      url = "jdbc:postgresql://postgres.postgres.svc.cluster.local:5432/waltid_wallet"
      user = "waltid"
      password = "waltid"
    }
  auth.conf: |
    auth {
      enabled = false
    }
  web.conf: |
    web {
      host = "0.0.0.0"
      port = 7001
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "eu-jap-hack.fullname" . }}-waltid-issuer
  labels:
    {{- include "eu-jap-hack.labels" . | nindent 4 }}
    app.kubernetes.io/component: waltid-issuer-api
data:
  issuer-service.conf: |
    issuer-service {
      baseUrl = "http://{{ include "eu-jap-hack.fullname" . }}-waltid-issuer:{{ .Values.waltidIssuerApi.service.port }}"
    }
  web.conf: |
    web {
      host = "0.0.0.0"
      port = 7002
    }
  credential-issuer-metadata.conf: |
    credential-issuer-metadata {
      issuer = "did:web:issuer.local"
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "eu-jap-hack.fullname" . }}-waltid-verifier
  labels:
    {{- include "eu-jap-hack.labels" . | nindent 4 }}
    app.kubernetes.io/component: waltid-verifier-api
data:
  verifier-service.conf: |
    verifier-service {
      baseUrl = "http://{{ include "eu-jap-hack.fullname" . }}-waltid-verifier:{{ .Values.waltidVerifierApi.service.port }}"
    }
  web.conf: |
    web {
      host = "0.0.0.0"
      port = 7003
    }